name: run-tests

on:
  pull_request:
    types: ["opened", "synchronize"]
    branches-ignore:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Cache node_modules and cypress
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        id: run-tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=https://www.vistarmedia.com
          working-directory: "./"
          group: "E2E tests"
          install: true
          browser: chrome
